version: "3.6"
services:

  imixssample-db:
    image: postgres:9.6.1
    environment:
      POSTGRES_PASSWORD: adminadmin
      POSTGRES_DB: workflow-db
  
  imixssample-app:
    image: imixs/imixs-process-manager
    environment:
      MODEL_DEFAULT_DATA: "ticket.bpmn"
      TZ: "Europe/Berlin"
    ports:
      - "9080:9080"
      - "9443:9443"
      - "7777:7777"
#    volumes:
#      - ./docker/deployments:/config/dropins/   



    
#  imixsadmin:
#    image: imixs/imixs-admin
#    ports:
#      - "8888:8080"