# Start with OL runtime.
FROM icr.io/appcafe/open-liberty
#FROM icr.io/appcafe/open-liberty:24.0.0.12-kernel-slim-java17-openj9
#FROM openliberty/open-liberty:kernel-java8-openj9-ubi



#FROM icr.io/appcafe/open-liberty:24.0.0.12-kernel-slim-java17-openj9-ubi




ARG VERSION=1.0
ARG REVISION=SNAPSHOT

LABEL \
  org.opencontainers.image.authors="Imixs-Workflow" \
  org.opencontainers.image.vendor="Imixs" \
  org.opencontainers.image.url="local" \
  org.opencontainers.image.source="https://github.com/imixs/imixs-process-manager" \
  org.opencontainers.image.version="$VERSION" \
  org.opencontainers.image.revision="$REVISION" \
  vendor="Open Liberty" \
  name="system" \
  version="$VERSION-$REVISION" \
  summary="Imixs Process Manager" \
  description="This image contains the Imixs Process Manager microservice running with the Open Liberty runtime."

USER root

# Copy postgres JDBC driver
#COPY ./docker/configuration/openliberty/postgresql-9.4.1212.jar /opt/ol/wlp/lib
COPY ./docker/configuration/openliberty/postgresql-42.2.5.jar /opt/ol/wlp/lib

COPY --chown=1001:0 ./docker/configuration/openliberty/server.xml /config/
COPY --chown=1001:0 ./target/*.war /config/apps/
#COPY --chown=1001:0 ./target/*.war /config/dropins/


USER 1001
