version: "3.6"
services:

  imixs-db:
    image: postgres:9.6.1
    environment:
      POSTGRES_PASSWORD: adminadmin
      POSTGRES_DB: workflow-db
    volumes: 
      - dbdata:/var/lib/postgresql/data


  
  imixs-app:
    image: imixs/imixs-process-manager
    environment:
      TZ: "CET" 
      LANG: "en_US.UTF-8"  
      JAVA_OPTS: "-Dnashorn.args=--no-deprecation-warning"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "adminadmin"
      POSTGRES_CONNECTION: "jdbc:postgresql://imixs-db/libreoffice-appworkflow-db"

      WOPI_DISCOVERY_ENDPOINT: "http://libreoffice-app:9980/hosting/discovery"
      WOPI_HOST_ENDPOINT: "http://imixs-app:8080//api/wopi/"
   
    ports:
      - "8080:8080"
      - "8787:8787"
      - "9990:9990"
      - "8443:8443"
    volumes:
      - ./docker/deployments:/opt/jboss/wildfly/standalone/deployments/
      - ./docker/test.odt:/opt/jbos/test.odt


  libreoffice-app:
    image: collabora/code:6.4.8.4
    container_name: libreoffice-app
    expose:
      - 9980
    ports:
      - "9980:9980"
    environment:
      - username=admin
      - password=adminadmin
    volumes:
      - ./loolwsd.xml:/etc/loolwsd/loolwsd.xml
    restart: always

      
volumes:
  dbdata:   